spring:
  application:
    name: gateway-service

server:
  port: 8762

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  ignored-services: '*'
  routes:
    auth-service:
      path: /auth/**
      service-id: auth-service
    workspace-service:
      path: /workspace/**
      service-id: workspace-service

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 600000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
