server:
  port: 8762

eureka:
  instance:
    instance-id: gateway-${random.uuid}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
        - id: customer-service
          uri: lb://workspace-service
          predicates:
            - Path=/workspace/**
          filters:
            - RewritePath=/workspace/(?<path>.*), /$\{path}

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 600000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS