spring:
  application:
    name: auth-service
  data:
    mongodb:
      database: auth
      uri: mongodb://192.168.99.100:27017

server:
  port: 9100

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
