spring:
  application:
    name: discovery-server
  boot:
    admin:
      context-path: /admin

server:
  port: 8761

eureka:
  instance:
    instance-id: discovery-${random.uuid}
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: false
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS
