spring:
  application:
    name: workspace-service

server:
  port: 9200

eureka:
  instance:
    instance-id: workspace-${random.uuid}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS